version: '3.1'

services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - .:/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: ./docker/php
        container_name: php
        working_dir: /app
        volumes:
            - .:/app
        links:
            - db

    db:
        image: mysql:5.7
        container_name: db
        ports:
            - "8306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        env_file:
            - ./.env
